# Generated by Django 3.1.7 on 2021-02-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
