# Generated by Django 3.1.7 on 2021-02-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_currency_disp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='disp',
            field=models.CharField(blank=True, default='y.e.', max_length=20, null=True),
        ),
    ]
