# Generated by Django 3.1.7 on 2021-03-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('cancel', 'Отменен'), ('processing', 'В обработке'), ('finished', 'Завершен')], default='new', max_length=50)),
                ('rate_currency', models.FloatField(default=1)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.currency')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_good', models.IntegerField(default=1)),
                ('title_good', models.CharField(default='Noname', max_length=300)),
                ('cost', models.FloatField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
            ],
        ),
    ]
