# Generated by Django 3.1.7 on 2021-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210311_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
