# Generated by Django 3.1.7 on 2021-03-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_orderitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_amount_on_curr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_on_curr',
            field=models.FloatField(default=0),
        ),
    ]
