# Generated by Django 3.1.7 on 2021-03-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210313_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_on_curr',
            field=models.FloatField(default=1),
        ),
    ]
