# Generated by Django 3.1.7 on 2021-03-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('cancel_order', 'change_status'),)},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('finished', 'Завершен'), ('cancel', 'Отменен')], default='new', max_length=50),
        ),
    ]
