# Generated by Django 3.1.7 on 2021-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210314_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('type_code', models.CharField(choices=[('fixed', 'Фиксированная'), ('relative', 'Относительная')], default='fixed', max_length=50)),
                ('amount_of_discount', models.FloatField(default=0)),
                ('type_promo', models.CharField(choices=[('onceuse', 'Одноразовые'), ('reusable', 'Многоразовые')], default='reusable', max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
