# Generated by Django 3.1.7 on 2021-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_order_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
