# Generated by Django 3.1.7 on 2021-03-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20210314_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='end_promo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='start_promo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
