# Generated by Django 3.1.7 on 2021-03-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210315_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
