# Generated by Django 3.1.7 on 2021-03-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cid',
            field=models.ManyToManyField(related_name='category', to='product.Categories'),
        ),
    ]
