# Generated by Django 3.1.7 on 2021-04-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210326_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_digit',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('material', 'Материальный'), ('file', 'Файл')], default='material', max_length=100),
        ),
    ]
