# Generated by Django 3.1.7 on 2021-04-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20210410_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_digit',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='Файл (при тип товара - Файл)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('material', 'Материальный'), ('file', 'Файл')], default='material', max_length=100, verbose_name='Тип товара'),
        ),
    ]
