# Generated by Django 3.1.7 on 2021-04-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20210410_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_digit',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл (при тип товара - Файл)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
