# Generated by Django 3.1.7 on 2021-04-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_filetelegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name matrix', max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='PriceMatrixItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(default=0, verbose_name='От')),
                ('max_value', models.FloatField(default=0, verbose_name='До')),
                ('type_item', models.CharField(choices=[('relative', 'В процентах'), ('fixed', 'Фиксированная')], default='fixed', max_length=50, verbose_name='Тип')),
                ('value', models.FloatField(default=0, verbose_name='Значение')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.pricematrix')),
            ],
        ),
    ]
