# Generated by Django 3.1.7 on 2021-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_delivery_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_of_delivery',
            field=models.FloatField(default=0),
        ),
    ]
