# Generated by Django 3.1.7 on 2021-04-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_of_delivery_on_curr',
            field=models.FloatField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost_of_delivery',
            field=models.FloatField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.delivery', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_amount',
            field=models.FloatField(default=0, verbose_name='Полная стоимость товаров в у.е.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_amount_on_curr',
            field=models.FloatField(default=0, verbose_name='Полная стоимость товаров с учетом курса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='product.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate_currency',
            field=models.FloatField(default=1, verbose_name='Курс валюты в момент заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('finished', 'Завершен'), ('cancel', 'Отменен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0, verbose_name='Сумма к оплате в у.е.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount_on_curr',
            field=models.FloatField(default=0, verbose_name='Сумма к оплате с учетом курса'),
        ),
    ]
