# Generated by Django 3.1.7 on 2021-04-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20210417_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'permissions': (('show_all_baskets', 'Просматривать корзины других пользователей'),)},
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='title',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
