# Generated by Django 3.1.7 on 2021-04-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20210418_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cost_on_curr',
        ),
    ]
