# Generated by Django 3.1.7 on 2021-04-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20210420_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Было ли списание средств.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('paid', 'Оплачен'), ('finished', 'Завершен'), ('cancel', 'Отменен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
