# Generated by Django 3.1.7 on 2021-04-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20210425_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCitiesNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('city_ua', models.CharField(blank=True, max_length=150, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('region_ua', models.CharField(blank=True, max_length=200, null=True)),
                ('city_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('cityID', models.IntegerField(default=0)),
            ],
        ),
    ]
