# Generated by Django 3.1.7 on 2021-04-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_deliverycitiesnp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryWarehousesNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitekey', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('description_ru', models.CharField(blank=True, default='', max_length=250)),
                ('short_address', models.CharField(blank=True, default='', max_length=250)),
                ('short_address_ru', models.CharField(blank=True, default='', max_length=250)),
                ('ref_warehouse', models.CharField(blank=True, default='', max_length=250)),
                ('number_warehouse', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.deliverycitiesnp')),
            ],
        ),
    ]
