# Generated by Django 3.1.7 on 2021-04-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_deliverywarehousesnp'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='type_delivery',
            field=models.CharField(default='normal', max_length=50, verbose_name='Тип (для сторонних интеграций)'),
        ),
    ]
