# Generated by Django 3.1.7 on 2021-04-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_delivery_type_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_department',
            field=models.CharField(blank='', max_length=400, null=True, verbose_name='Информация об адресе доставки.'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type_delivery',
            field=models.CharField(choices=[('normal', 'Обычный'), ('np', 'NovaPoshta')], default='normal', max_length=50, verbose_name='Тип (для сторонних интеграций)'),
        ),
    ]
