# Generated by Django 3.1.7 on 2021-04-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20210427_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_department',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Информация об адресе доставки.'),
        ),
    ]
