# Generated by Django 3.1.7 on 2022-02-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_auto_20210504_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'permissions': (('show_all_wishlist', 'Просматривать список желаний других пользователей'),)},
        ),
    ]
