# Generated by Django 3.1.7 on 2021-04-04 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_tg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_promo', models.BooleanField(default=False)),
                ('is_answer_support', models.BooleanField(default=True)),
                ('is_create_order', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
