# Generated by Django 3.1.7 on 2021-04-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210404_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='is_answer_support',
            field=models.BooleanField(default=False, verbose_name='Уведомления об ответе службы поддержки'),
        ),
    ]
