# Generated by Django 3.1.7 on 2021-04-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210410_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='is_get_digit_file',
            field=models.BooleanField(default=False, verbose_name='Получать цифровые файлы с заказа'),
        ),
    ]
