# Generated by Django 3.1.7 on 2021-04-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscribe_is_get_digit_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='is_authorization',
            field=models.BooleanField(default=False, verbose_name='Успешной авторизации в аккаунт'),
        ),
    ]
