# Generated by Django 3.1.7 on 2021-03-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('open', 'Открытый'), ('close', 'Закрыт'), ('reminder', 'В напоминании'), ('answer', 'Отвечен')], default='new', max_length=30),
        ),
    ]
